server:
  port: 8090

spring:
  application:
    name: irctc-api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
