# Booking Service Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

# Booking Service Specific Settings
booking:
  batch:
    confirmation:
      interval-ms: 1800000  # 30 minutes
      batch-size: 100
  idempotency:
    key-expiry-hours: 24

logging:
  level:
    com.irctc.booking: INFO

