# User Service Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# User Service Specific Settings
security:
  jwt:
    secret: ${JWT_SECRET:irctc-user-service-secret-key-2024}
    expiration: 86400000
  password:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-digits: true
    require-special-chars: true

logging:
  level:
    com.irctc.user: INFO

