# Notification Service Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Notification Service Specific Settings
notification:
  email:
    enabled: true
    from: noreply@irctc.com
  sms:
    enabled: false
  push:
    enabled: true
  dlq:
    max-retries: 3
    retry-delay-ms: 5000

logging:
  level:
    com.irctc.notification: INFO

