server:
  port: 8761

spring:
  application:
    name: irctc-eureka-server
  cloud:
    compatibility-verifier:
      enabled: false

# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

# Logging Configuration
logging:
  level:
    com.irctc.eureka: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/irctc-eureka-server.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
