# Payment Service Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Payment Service Specific Settings
payment:
  razorpay:
    key-id: ${RAZORPAY_KEY_ID:demo-key}
    key-secret: ${RAZORPAY_KEY_SECRET:demo-secret}
  refund:
    allowed-hours: 72

logging:
  level:
    com.irctc.payment: INFO

